services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    ports:
      - "8081:8081"
#  Uncomment for running in docker container
#  popper_server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "5029:5029"
#    depends_on:
#      - mongo
#      - minio
#      - adminer
#      - db
#    restart: on-failure
#    stop_grace_period: 5s
